<?php

namespace Database\Seeders;

use App\Models\TransactionType;
use Illuminate\Database\Seeder;

class TransactionTypesSeeder extends Seeder
{
    public function run()
    {

        $transactionTypes = [
            [
                "id" => 1,
                "key" => "INCOME",
                "detailed" => "INCOME_DIVIDENDS",
                "description" => "Dividends from investment accounts",
            ],
            [
                "id" => 2,
                "key" => "INCOME",
                "detailed" => "INCOME_INTEREST_EARNED",
                "description" => "Income from interest on savings accounts",
            ],
            [
                "id" => 3,
                "key" => "INCOME",
                "detailed" => "INCOME_RETIREMENT_PENSION",
                "description" => "Income from pension payments ",
            ],
            [
                "id" => 4,
                "key" => "INCOME",
                "detailed" => "INCOME_TAX_REFUND",
                "description" => "Income from tax refunds",
            ],
            [
                "id" => 5,
                "key" => "INCOME",
                "detailed" => "INCOME_UNEMPLOYMENT",
                "description" => "Income from unemployment benefits, including unemployment insurance and healthcare",
            ],
            [
                "id" => 6,
                "key" => "INCOME",
                "detailed" => "INCOME_WAGES",
                "description" => "Income from salaries, gig-economy work, and tips earned",
            ],
            [
                "id" => 7,
                "key" => "INCOME",
                "detailed" => "INCOME_OTHER_INCOME",
                "description" => "Other miscellaneous income, including alimony, social security, child support, and rental",
            ],
            [
                "id" => 8,
                "key" => "TRANSFER_IN",
                "detailed" => "TRANSFER_IN_CASH_ADVANCES_AND_LOANS",
                "description" => "Loans and cash advances deposited into a bank account",
            ],
            [
                "id" => 9,
                "key" => "TRANSFER_IN",
                "detailed" => "TRANSFER_IN_DEPOSIT",
                "description" => "Cash, checks, and ATM deposits into a bank account",
            ],
            [
                "id" => 10,
                "key" => "TRANSFER_IN",
                "detailed" => "TRANSFER_IN_INVESTMENT_AND_RETIREMENT_FUNDS",
                "description" => "Inbound transfers to an investment or retirement account",
            ],
            [
                "id" => 11,
                "key" => "TRANSFER_IN",
                "detailed" => "TRANSFER_IN_SAVINGS",
                "description" => "Inbound transfers to a savings account",
            ],
            [
                "id" => 12,
                "key" => "TRANSFER_IN",
                "detailed" => "TRANSFER_IN_ACCOUNT_TRANSFER",
                "description" => "General inbound transfers from another account",
            ],
            [
                "id" => 13,
                "key" => "TRANSFER_IN",
                "detailed" => "TRANSFER_IN_OTHER_TRANSFER_IN",
                "description" => "Other miscellaneous inbound transactions",
            ],
            [
                "id" => 14,
                "key" => "TRANSFER_OUT",
                "detailed" => "TRANSFER_OUT_INVESTMENT_AND_RETIREMENT_FUNDS",
                "description" => "Transfers to an investment or retirement account, including investment apps such as Acorns, Betterment",
            ],
            [
                "id" => 15,
                "key" => "TRANSFER_OUT",
                "detailed" => "TRANSFER_OUT_SAVINGS",
                "description" => "Outbound transfers to savings accounts",
            ],
            [
                "id" => 16,
                "key" => "TRANSFER_OUT",
                "detailed" => "TRANSFER_OUT_WITHDRAWAL",
                "description" => "Withdrawals from a bank account",
            ],
            [
                "id" => 17,
                "key" => "TRANSFER_OUT",
                "detailed" => "TRANSFER_OUT_ACCOUNT_TRANSFER",
                "description" => "General outbound transfers to another account",
            ],
            [
                "id" => 18,
                "key" => "TRANSFER_OUT",
                "detailed" => "TRANSFER_OUT_OTHER_TRANSFER_OUT",
                "description" => "Other miscellaneous outbound transactions",
            ],
            [
                "id" => 19,
                "key" => "LOAN_PAYMENTS",
                "detailed" => "LOAN_PAYMENTS_CAR_PAYMENT",
                "description" => "Car loans and leases",
            ],
            [
                "id" => 20,
                "key" => "LOAN_PAYMENTS",
                "detailed" => "LOAN_PAYMENTS_CREDIT_CARD_PAYMENT",
                "description" => "Payments to a credit card. These are positive amounts for credit card subtypes and negative for depository subtypes",
            ],
            [
                "id" => 21,
                "key" => "LOAN_PAYMENTS",
                "detailed" => "LOAN_PAYMENTS_PERSONAL_LOAN_PAYMENT",
                "description" => "Personal loans, including cash advances and buy now pay later repayments",
            ],
            [
                "id" => 22,
                "key" => "LOAN_PAYMENTS",
                "detailed" => "LOAN_PAYMENTS_MORTGAGE_PAYMENT",
                "description" => "Payments on mortgages",
            ],
            [
                "id" => 23,
                "key" => "LOAN_PAYMENTS",
                "detailed" => "LOAN_PAYMENTS_STUDENT_LOAN_PAYMENT",
                "description" => "Payments on student loans. For college tuition, refer to \"General Services - Education\"",
            ],
            [
                "id" => 24,
                "key" => "LOAN_PAYMENTS",
                "detailed" => "LOAN_PAYMENTS_OTHER_PAYMENT",
                "description" => "Other miscellaneous debt payments",
            ],
            [
                "id" => 25,
                "key" => "BANK_FEES",
                "detailed" => "BANK_FEES_ATM_FEES",
                "description" => "Fees incurred for out-of-network ATMs",
            ],
            [
                "id" => 26,
                "key" => "BANK_FEES",
                "detailed" => "BANK_FEES_FOREIGN_TRANSACTION_FEES",
                "description" => "Fees incurred on non-domestic transactions",
            ],
            [
                "id" => 27,
                "key" => "BANK_FEES",
                "detailed" => "BANK_FEES_INSUFFICIENT_FUNDS",
                "description" => "Fees relating to insufficient funds",
            ],
            [
                "id" => 28,
                "key" => "BANK_FEES",
                "detailed" => "BANK_FEES_INTEREST_CHARGE",
                "description" => "Fees incurred for interest on purchases, including not-paid-in-full or interest on cash advances",
            ],
            [
                "id" => 29,
                "key" => "BANK_FEES",
                "detailed" => "BANK_FEES_OVERDRAFT_FEES",
                "description" => "Fees incurred when an account is in overdraft",
            ],
            [
                "id" => 30,
                "key" => "BANK_FEES",
                "detailed" => "BANK_FEES_OTHER_BANK_FEES",
                "description" => "Other miscellaneous bank fees",
            ],
            [
                "id" => 31,
                "key" => "ENTERTAINMENT",
                "detailed" => "ENTERTAINMENT_CASINOS_AND_GAMBLING",
                "description" => "Gambling, casinos, and sports betting",
            ],
            [
                "id" => 32,
                "key" => "ENTERTAINMENT",
                "detailed" => "ENTERTAINMENT_MUSIC_AND_AUDIO",
                "description" => "Digital and in-person music purchases, including music streaming services",
            ],
            [
                "id" => 33,
                "key" => "ENTERTAINMENT",
                "detailed" => "ENTERTAINMENT_SPORTING_EVENTS_AMUSEMENT_PARKS_AND_MUSEUMS",
                "description" => "Purchases made at sporting events, music venues, concerts, museums, and amusement parks",
            ],
            [
                "id" => 34,
                "key" => "ENTERTAINMENT",
                "detailed" => "ENTERTAINMENT_TV_AND_MOVIES",
                "description" => "In home movie streaming services and movie theaters",
            ],
            [
                "id" => 35,
                "key" => "ENTERTAINMENT",
                "detailed" => "ENTERTAINMENT_VIDEO_GAMES",
                "description" => "Digital and in-person video game purchases",
            ],
            [
                "id" => 36,
                "key" => "ENTERTAINMENT",
                "detailed" => "ENTERTAINMENT_OTHER_ENTERTAINMENT",
                "description" => "Other miscellaneous entertainment purchases, including night life and adult entertainment",
            ],
            [
                "id" => 37,
                "key" => "FOOD_AND_DRINK",
                "detailed" => "FOOD_AND_DRINK_BEER_WINE_AND_LIQUOR",
                "description" => "Beer, Wine & Liquor Stores",
            ],
            [
                "id" => 38,
                "key" => "FOOD_AND_DRINK",
                "detailed" => "FOOD_AND_DRINK_COFFEE",
                "description" => "Purchases at coffee shops or cafes",
            ],
            [
                "id" => 39,
                "key" => "FOOD_AND_DRINK",
                "detailed" => "FOOD_AND_DRINK_FAST_FOOD",
                "description" => "Dining expenses for fast food chains",
            ],
            [
                "id" => 40,
                "key" => "FOOD_AND_DRINK",
                "detailed" => "FOOD_AND_DRINK_GROCERIES",
                "description" => "Purchases for fresh produce and groceries, including farmers' markets",
            ],
            [
                "id" => 41,
                "key" => "FOOD_AND_DRINK",
                "detailed" => "FOOD_AND_DRINK_RESTAURANT",
                "description" => "Dining expenses for restaurants, bars, gastropubs, and diners",
            ],
            [
                "id" => 42,
                "key" => "FOOD_AND_DRINK",
                "detailed" => "FOOD_AND_DRINK_VENDING_MACHINES",
                "description" => "Purchases made at vending machine operators",
            ],
            [
                "id" => 43,
                "key" => "FOOD_AND_DRINK",
                "detailed" => "FOOD_AND_DRINK_OTHER_FOOD_AND_DRINK",
                "description" => "Other miscellaneous food and drink, including desserts, juice bars, and delis",
            ],
            [
                "id" => 44,
                "key" => "GENERAL_MERCHANDISE",
                "detailed" => "GENERAL_MERCHANDISE_BOOKSTORES_AND_NEWSSTANDS",
                "description" => "Books, magazines, and news ",
            ],
            [
                "id" => 45,
                "key" => "GENERAL_MERCHANDISE",
                "detailed" => "GENERAL_MERCHANDISE_CLOTHING_AND_ACCESSORIES",
                "description" => "Apparel, shoes, and jewelry",
            ],
            [
                "id" => 46,
                "key" => "GENERAL_MERCHANDISE",
                "detailed" => "GENERAL_MERCHANDISE_CONVENIENCE_STORES",
                "description" => "Purchases at convenience stores",
            ],
            [
                "id" => 47,
                "key" => "GENERAL_MERCHANDISE",
                "detailed" => "GENERAL_MERCHANDISE_DEPARTMENT_STORES",
                "description" => "Retail stores with wide ranges of consumer goods, typically specializing in clothing and home goods",
            ],
            [
                "id" => 48,
                "key" => "GENERAL_MERCHANDISE",
                "detailed" => "GENERAL_MERCHANDISE_DISCOUNT_STORES",
                "description" => "Stores selling goods at a discounted price",
            ],
            [
                "id" => 49,
                "key" => "GENERAL_MERCHANDISE",
                "detailed" => "GENERAL_MERCHANDISE_ELECTRONICS",
                "description" => "Electronics stores and websites",
            ],
            [
                "id" => 50,
                "key" => "GENERAL_MERCHANDISE",
                "detailed" => "GENERAL_MERCHANDISE_GIFTS_AND_NOVELTIES",
                "description" => "Photo, gifts, cards, and floral stores",
            ],
            [
                "id" => 51,
                "key" => "GENERAL_MERCHANDISE",
                "detailed" => "GENERAL_MERCHANDISE_OFFICE_SUPPLIES",
                "description" => "Stores that specialize in office goods",
            ],
            [
                "id" => 52,
                "key" => "GENERAL_MERCHANDISE",
                "detailed" => "GENERAL_MERCHANDISE_ONLINE_MARKETPLACES",
                "description" => "Multi-purpose e-commerce platforms such as Etsy, Ebay and Amazon",
            ],
            [
                "id" => 53,
                "key" => "GENERAL_MERCHANDISE",
                "detailed" => "GENERAL_MERCHANDISE_PET_SUPPLIES",
                "description" => "Pet supplies and pet food",
            ],
            [
                "id" => 54,
                "key" => "GENERAL_MERCHANDISE",
                "detailed" => "GENERAL_MERCHANDISE_SPORTING_GOODS",
                "description" => "Sporting goods, camping gear, and outdoor equipment",
            ],
            [
                "id" => 55,
                "key" => "GENERAL_MERCHANDISE",
                "detailed" => "GENERAL_MERCHANDISE_SUPERSTORES",
                "description" => "Superstores such as Target and Walmart, selling both groceries and general merchandise",
            ],
            [
                "id" => 56,
                "key" => "GENERAL_MERCHANDISE",
                "detailed" => "GENERAL_MERCHANDISE_TOBACCO_AND_VAPE",
                "description" => "Purchases for tobacco and vaping products",
            ],
            [
                "id" => 57,
                "key" => "GENERAL_MERCHANDISE",
                "detailed" => "GENERAL_MERCHANDISE_OTHER_GENERAL_MERCHANDISE",
                "description" => "Other miscellaneous merchandise, including toys, hobbies, and arts and crafts",
            ],
            [
                "id" => 58,
                "key" => "HOME_IMPROVEMENT",
                "detailed" => "HOME_IMPROVEMENT_FURNITURE",
                "description" => "Furniture, bedding, and home accessories",
            ],
            [
                "id" => 59,
                "key" => "HOME_IMPROVEMENT",
                "detailed" => "HOME_IMPROVEMENT_HARDWARE",
                "description" => "Building materials, hardware stores, paint, and wallpaper",
            ],
            [
                "id" => 60,
                "key" => "HOME_IMPROVEMENT",
                "detailed" => "HOME_IMPROVEMENT_REPAIR_AND_MAINTENANCE",
                "description" => "Plumbing, lighting, gardening, and roofing",
            ],
            [
                "id" => 61,
                "key" => "HOME_IMPROVEMENT",
                "detailed" => "HOME_IMPROVEMENT_SECURITY",
                "description" => "Home security system purchases",
            ],
            [
                "id" => 62,
                "key" => "HOME_IMPROVEMENT",
                "detailed" => "HOME_IMPROVEMENT_OTHER_HOME_IMPROVEMENT",
                "description" => "Other miscellaneous home purchases, including pool installation and pest control",
            ],
            [
                "id" => 63,
                "key" => "MEDICAL",
                "detailed" => "MEDICAL_DENTAL_CARE",
                "description" => "Dentists and general dental care",
            ],
            [
                "id" => 64,
                "key" => "MEDICAL",
                "detailed" => "MEDICAL_EYE_CARE",
                "description" => "Optometrists, contacts, and glasses stores",
            ],
            [
                "id" => 65,
                "key" => "MEDICAL",
                "detailed" => "MEDICAL_NURSING_CARE",
                "description" => "Nursing care and facilities",
            ],
            [
                "id" => 66,
                "key" => "MEDICAL",
                "detailed" => "MEDICAL_PHARMACIES_AND_SUPPLEMENTS",
                "description" => "Pharmacies and nutrition shops",
            ],
            [
                "id" => 67,
                "key" => "MEDICAL",
                "detailed" => "MEDICAL_PRIMARY_CARE",
                "description" => "Doctors and physicians",
            ],
            [
                "id" => 68,
                "key" => "MEDICAL",
                "detailed" => "MEDICAL_VETERINARY_SERVICES",
                "description" => "Prevention and care procedures for animals",
            ],
            [
                "id" => 69,
                "key" => "MEDICAL",
                "detailed" => "MEDICAL_OTHER_MEDICAL",
                "description" => "Other miscellaneous medical, including blood work, hospitals, and ambulances",
            ],
            [
                "id" => 70,
                "key" => "PERSONAL_CARE",
                "detailed" => "PERSONAL_CARE_GYMS_AND_FITNESS_CENTERS",
                "description" => "Gyms, fitness centers, and workout classes",
            ],
            [
                "id" => 71,
                "key" => "PERSONAL_CARE",
                "detailed" => "PERSONAL_CARE_HAIR_AND_BEAUTY",
                "description" => "Manicures, haircuts, waxing, spa/massages, and bath and beauty products ",
            ],
            [
                "id" => 72,
                "key" => "PERSONAL_CARE",
                "detailed" => "PERSONAL_CARE_LAUNDRY_AND_DRY_CLEANING",
                "description" => "Wash and fold, and dry cleaning expenses",
            ],
            [
                "id" => 73,
                "key" => "PERSONAL_CARE",
                "detailed" => "PERSONAL_CARE_OTHER_PERSONAL_CARE",
                "description" => "Other miscellaneous personal care, including mental health apps and services",
            ],
            [
                "id" => 74,
                "key" => "GENERAL_SERVICES",
                "detailed" => "GENERAL_SERVICES_ACCOUNTING_AND_FINANCIAL_PLANNING",
                "description" => "Financial planning, and tax and accounting services",
            ],
            [
                "id" => 75,
                "key" => "GENERAL_SERVICES",
                "detailed" => "GENERAL_SERVICES_AUTOMOTIVE",
                "description" => "Oil changes, car washes, repairs, and towing",
            ],
            [
                "id" => 76,
                "key" => "GENERAL_SERVICES",
                "detailed" => "GENERAL_SERVICES_CHILDCARE",
                "description" => "Babysitters and daycare",
            ],
            [
                "id" => 77,
                "key" => "GENERAL_SERVICES",
                "detailed" => "GENERAL_SERVICES_CONSULTING_AND_LEGAL",
                "description" => "Consulting and legal services",
            ],
            [
                "id" => 78,
                "key" => "GENERAL_SERVICES",
                "detailed" => "GENERAL_SERVICES_EDUCATION",
                "description" => "Elementary, high school, professional schools, and college tuition",
            ],
            [
                "id" => 79,
                "key" => "GENERAL_SERVICES",
                "detailed" => "GENERAL_SERVICES_INSURANCE",
                "description" => "Insurance for auto, home, and healthcare",
            ],
            [
                "id" => 80,
                "key" => "GENERAL_SERVICES",
                "detailed" => "GENERAL_SERVICES_POSTAGE_AND_SHIPPING",
                "description" => "Mail, packaging, and shipping services",
            ],
            [
                "id" => 81,
                "key" => "GENERAL_SERVICES",
                "detailed" => "GENERAL_SERVICES_STORAGE",
                "description" => "Storage services and facilities",
            ],
            [
                "id" => 82,
                "key" => "GENERAL_SERVICES",
                "detailed" => "GENERAL_SERVICES_OTHER_GENERAL_SERVICES",
                "description" => "Other miscellaneous services, including advertising and cloud storage ",
            ],
            [
                "id" => 83,
                "key" => "GOVERNMENT_AND_NON_PROFIT",
                "detailed" => "GOVERNMENT_AND_NON_PROFIT_DONATIONS",
                "description" => "Charitable, political, and religious donations",
            ],
            [
                "id" => 84,
                "key" => "GOVERNMENT_AND_NON_PROFIT",
                "detailed" => "GOVERNMENT_AND_NON_PROFIT_GOVERNMENT_DEPARTMENTS_AND_AGENCIES",
                "description" => "Government departments and agencies, such as driving licences, and passport renewal",
            ],
            [
                "id" => 85,
                "key" => "GOVERNMENT_AND_NON_PROFIT",
                "detailed" => "GOVERNMENT_AND_NON_PROFIT_TAX_PAYMENT",
                "description" => "Tax payments, including income and property taxes",
            ],
            [
                "id" => 86,
                "key" => "GOVERNMENT_AND_NON_PROFIT",
                "detailed" => "GOVERNMENT_AND_NON_PROFIT_OTHER_GOVERNMENT_AND_NON_PROFIT",
                "description" => "Other miscellaneous government and non-profit agencies",
            ],
            [
                "id" => 87,
                "key" => "TRANSPORTATION",
                "detailed" => "TRANSPORTATION_BIKES_AND_SCOOTERS",
                "description" => "Bike and scooter rentals",
            ],
            [
                "id" => 88,
                "key" => "TRANSPORTATION",
                "detailed" => "TRANSPORTATION_GAS",
                "description" => "Purchases at a gas station",
            ],
            [
                "id" => 89,
                "key" => "TRANSPORTATION",
                "detailed" => "TRANSPORTATION_PARKING",
                "description" => "Parking fees and expenses",
            ],
            [
                "id" => 90,
                "key" => "TRANSPORTATION",
                "detailed" => "TRANSPORTATION_PUBLIC_TRANSIT",
                "description" => "Public transportation, including rail and train, buses, and metro",
            ],
            [
                "id" => 91,
                "key" => "TRANSPORTATION",
                "detailed" => "TRANSPORTATION_TAXIS_AND_RIDE_SHARES",
                "description" => "Taxi and ride share services",
            ],
            [
                "id" => 92,
                "key" => "TRANSPORTATION",
                "detailed" => "TRANSPORTATION_TOLLS",
                "description" => "Toll expenses",
            ],
            [
                "id" => 93,
                "key" => "TRANSPORTATION",
                "detailed" => "TRANSPORTATION_OTHER_TRANSPORTATION",
                "description" => "Other miscellaneous transportation expenses",
            ],
            [
                "id" => 94,
                "key" => "TRAVEL",
                "detailed" => "TRAVEL_FLIGHTS",
                "description" => "Airline expenses",
            ],
            [
                "id" => 95,
                "key" => "TRAVEL",
                "detailed" => "TRAVEL_LODGING",
                "description" => "Hotels, motels, and hosted accommodation such as Airbnb",
            ],
            [
                "id" => 96,
                "key" => "TRAVEL",
                "detailed" => "TRAVEL_RENTAL_CARS",
                "description" => "Rental cars, charter buses, and trucks",
            ],
            [
                "id" => 97,
                "key" => "TRAVEL",
                "detailed" => "TRAVEL_OTHER_TRAVEL",
                "description" => "Other miscellaneous travel expenses",
            ],
            [
                "id" => 98,
                "key" => "RENT_AND_UTILITIES",
                "detailed" => "RENT_AND_UTILITIES_GAS_AND_ELECTRICITY",
                "description" => "Gas and electricity bills",
            ],
            [
                "id" => 99,
                "key" => "RENT_AND_UTILITIES",
                "detailed" => "RENT_AND_UTILITIES_INTERNET_AND_CABLE",
                "description" => "Internet and cable bills",
            ],
            [
                "id" => 100,
                "key" => "RENT_AND_UTILITIES",
                "detailed" => "RENT_AND_UTILITIES_RENT",
                "description" => "Rent payment",
            ],
            [
                "id" => 101,
                "key" => "RENT_AND_UTILITIES",
                "detailed" => "RENT_AND_UTILITIES_SEWAGE_AND_WASTE_MANAGEMENT",
                "description" => "Sewage and garbage disposal bills",
            ],
            [
                "id" => 102,
                "key" => "RENT_AND_UTILITIES",
                "detailed" => "RENT_AND_UTILITIES_TELEPHONE",
                "description" => "Cell phone bills",
            ],
            [
                "id" => 103,
                "key" => "RENT_AND_UTILITIES",
                "detailed" => "RENT_AND_UTILITIES_WATER",
                "description" => "Water bills",
            ],
            [
                "id" => 104,
                "key" => "RENT_AND_UTILITIES",
                "detailed" => "RENT_AND_UTILITIES_OTHER_UTILITIES",
                "description" => "Other miscellaneous utility bills",
            ],
        ];

        foreach ($transactionTypes as $transactionTypeData) {
            TransactionType::create($transactionTypeData);
        }
    }
}
